### ISSUE TITLE
Changing columns or rows count issue

### ISSUE THREAD

**Issue by mariovonleitmeritz** [capeisti/infinite-grid#11]
Problem1: Increment columns/rows count via setItemCount(int x, int y) has no effect to UI so a user can not scrolls to new items
Problem2: Decrement columns/rows count via setItemCount(int x, int y) leads to repeating items

**Comment by samulivaadin** [comment]
Added support for changing dimensions and properties during runtime along with possibility to do programmatically refresh. Please check version 0.7.
